# Generated by Django 5.1.4 on 2025-01-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="equipment/"),
        ),
        migrations.AlterField(
            model_name="field",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="fields/"),
        ),
    ]
