# Generated by Django 5.1.4 on 2025-01-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0002_alter_equipment_img_alter_field_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
    ]
